import { useState } from 'react'
import { Link, Navigate, Route, Routes, useParams } from 'react-router-dom'
import { AuthForm, CategoryFilter, EmptyState, Header, MapPlaceholder, PointForm, PointList, ProjectCard, ProjectForm } from './components'
import { categories, points, projects, type Point } from './data'

function HomePage() {
  const features = [
    ['調査地点を記録', '地図をクリックして、店舗・空き店舗・公共施設などを登録できます。'],
    ['地図で分布を確認', '登録地点を地図上で確認し、カテゴリごとに表示を切り替えられます。'],
    ['地域の特徴を考える', '地点の分布を見ながら、なぜその場所に集中しているのかを考察できます。'],
  ]
  return <><Header /><main><section className="border-b border-line bg-surface"><div className="shell grid items-center gap-12 py-16 md:grid-cols-[1.05fr_.95fr] md:py-24"><div><p className="mb-4 text-sm font-bold tracking-widest text-accent">FIELDWORK × WEB GIS</p><h1 className="max-w-2xl font-heading text-4xl font-bold leading-tight tracking-tight text-balance text-ink md:text-5xl">フィールドワークの記録を、地図で振り返ろう</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted">調査した店舗や施設などを地図に登録し、分布や地域の特徴を確認できる学習用WebGISです。</p><div className="mt-8 flex flex-wrap items-center gap-5"><Link className="button-primary px-6" to="/signup">無料で始める</Link><Link className="text-link text-sm" to="/login">すでにアカウントをお持ちの方 → ログイン</Link></div></div><div className="map-area min-h-80" aria-label="地図のイメージ"><div className="map-label">調査地点の分布イメージ</div><div className="road road-a"/><div className="road road-b"/><span className="map-pin pin-a"/><span className="map-pin pin-b"/></div></div></section><section className="shell py-16"><p className="text-sm font-bold text-accent">できること</p><h2 className="mt-2 font-heading text-2xl font-bold text-ink">観察した事実を、地域の理解につなげる</h2><div className="mt-8 grid gap-px overflow-hidden rounded-md border border-line bg-line md:grid-cols-3">{features.map(([title, description], index) => <article className="bg-surface p-7" key={title}><span className="text-xs font-bold text-brand">STEP {index + 1}</span><h3 className="mt-3 font-heading text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{description}</p></article>)}</div><div className="mt-12 flex flex-wrap items-center justify-center gap-3 rounded-md bg-brand px-6 py-7 text-center text-sm font-bold text-surface"><span>現地調査</span><span aria-hidden="true">→</span><span>地図に登録</span><span aria-hidden="true">→</span><span>分布を確認</span><span aria-hidden="true">→</span><span>地域について考察</span></div></section></main></>
}

function AuthPage({ signup = false }: { signup?: boolean }) { return <><Header /><main className="shell flex min-h-[calc(100vh-64px)] items-start justify-center py-12 md:items-center md:py-16"><div className="w-full max-w-md"><AuthForm signup={signup} /></div></main></> }

function ProjectsPage() {
  const [showEmpty, setShowEmpty] = useState(false)
  return <><Header authenticated /><main className="shell py-10 md:py-14"><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-heading text-3xl font-bold text-ink">調査プロジェクト</h1><p className="mt-2 text-sm text-muted">フィールドワークごとに調査地点を管理できます。</p></div><Link className="button-primary" to="/projects/new">+ 新しいプロジェクト</Link></div><div className="mt-6 flex justify-end"><button className="text-link text-xs" type="button" onClick={() => setShowEmpty(!showEmpty)}>デザイン確認：{showEmpty ? '一覧' : '空状態'}を表示</button></div>{showEmpty ? <div className="mt-6"><EmptyState title="まだ調査プロジェクトがありません。" description="まずはフィールドワーク用のプロジェクトを作成してみましょう。" action="最初のプロジェクトを作成" to="/projects/new" /></div> : <div className="mt-6 grid gap-5 md:grid-cols-2">{projects.map(project => <ProjectCard key={project.id} project={project} />)}</div>}</main></>
}

function ProjectFormPage({ editing = false }: { editing?: boolean }) { return <><Header authenticated /><main className="shell max-w-3xl py-10 md:py-14"><Link className="text-link text-sm" to="/projects">← プロジェクト一覧へ</Link><h1 className="mt-6 font-heading text-3xl font-bold text-ink">{editing ? '調査プロジェクトを編集' : '新しい調査プロジェクト'}</h1><p className="mt-2 text-sm text-muted">調査の目的が分かる名前と説明を入力してください。</p><div className="mt-8"><ProjectForm editing={editing} /></div></main></> }

function PointPopup({ point, onEdit, onDelete, onClose }: { point: Point; onEdit: () => void; onDelete: () => void; onClose: () => void }) {
  const [confirming, setConfirming] = useState(false)
  return <div className="popup" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between gap-3"><h3 className="font-heading font-bold text-ink">{point.name}</h3><button className="text-muted" aria-label="閉じる" type="button" onClick={onClose}>×</button></div>{confirming ? <div className="mt-4"><p className="text-sm font-bold">この地点を削除しますか？</p><div className="mt-4 flex gap-3"><button className="button-secondary flex-1 text-sm" type="button" onClick={() => setConfirming(false)}>戻る</button><button className="flex-1 rounded border border-danger px-3 py-2 text-sm font-bold text-danger" type="button" onClick={onDelete}>削除する</button></div></div> : <><dl className="mt-3 text-sm leading-6"><div><dt className="inline text-muted">カテゴリ：</dt><dd className="inline">{point.category}</dd></div><div><dt className="inline text-muted">調査日：</dt><dd className="inline">{point.surveyedAt.replaceAll('-', '/')}</dd></div></dl><p className="mt-3 border-t border-line pt-3 text-sm leading-6">{point.memo}</p><div className="mt-4 flex gap-4 text-sm"><button className="text-link" type="button" onClick={onEdit}>編集</button><button className="font-bold text-danger" type="button" onClick={() => setConfirming(true)}>削除</button></div></>}</div>
}

function MapPage() {
  const { id } = useParams()
  const project = projects.find(item => item.id === id) ?? projects[0]
  const [mode, setMode] = useState<'list'|'pick'|'create'|'edit'>('list')
  const [selected, setSelected] = useState<Point | undefined>()
  const [filters, setFilters] = useState(categories)
  const [notice, setNotice] = useState('')
  const [pointItems, setPointItems] = useState(points)
  const filtered = pointItems.filter(point => filters.includes(point.category))
  const instruction = mode === 'pick' ? '地図上で登録したい場所をクリックしてください' : mode === 'edit' ? undefined : undefined
  function save(message: string) { setMode('list'); setSelected(undefined); setNotice(message); window.setTimeout(() => setNotice(''), 2600) }
  function selectPoint(point: Point) { if (mode !== 'pick') { setSelected(pointItems.find(item => item.id === point.id) ?? point); setMode('list') } }
  return <><Header authenticated /><main className="flex min-h-[calc(100vh-64px)] flex-col"><div className="border-b border-line bg-surface"><div className="shell flex flex-wrap items-center justify-between gap-4 py-4"><div><Link className="text-link text-xs" to="/projects">← プロジェクト一覧へ戻る</Link><h1 className="mt-1 font-heading text-xl font-bold text-ink">{project.name}</h1></div><button className="button-primary md:hidden" type="button" onClick={() => { setMode('pick'); setSelected(undefined) }}>+ 地点を追加</button></div></div>{instruction && <div className="bg-brand px-4 py-3 text-center text-sm font-bold text-surface">{instruction}</div>}{notice && <div className="fixed right-4 top-20 z-20 rounded border border-accent bg-surface px-4 py-3 text-sm font-bold text-accent shadow-lg" role="status">{notice}</div>}<div className="flex flex-1 flex-col md:grid md:grid-cols-[340px_minmax(0,1fr)]"><aside className="order-2 border-r border-line bg-surface p-5 md:order-1 md:max-h-[calc(100vh-129px)] md:overflow-y-auto">{mode === 'create' ? <PointForm title="地点を登録" onCancel={() => setMode('list')} onSave={() => save('地点を登録しました')} /> : mode === 'edit' && selected ? <PointForm title="地点を編集" point={selected} onCancel={() => setMode('list')} onSave={() => save('地点情報を更新しました')} onRelocate={() => { setMode('pick'); setNotice('地図上で新しい位置をクリックしてください') }} /> : <div className="flex flex-col gap-6"><CategoryFilter selected={filters} onChange={setFilters} /><button className="button-primary hidden w-full md:inline-flex" type="button" onClick={() => { setMode('pick'); setSelected(undefined) }}>+ 地点を追加</button><PointList items={filtered} selectedId={selected?.id} onSelect={selectPoint} /><div className="border-t border-line pt-4"><p className="text-xs leading-5 text-muted">地点を選ぶと地図上に詳細が表示されます。表示件数やエラー状態はAPI接続時に差し替えられます。</p></div></div>}</aside><section className="order-1 min-w-0 bg-soft p-3 md:order-2 md:p-5"><MapPlaceholder selected={selected} picking={mode === 'pick'} onMapClick={() => setMode('create')} onSelect={selectPoint}>{selected && mode === 'list' && <PointPopup point={selected} onClose={() => setSelected(undefined)} onEdit={() => setMode('edit')} onDelete={() => { setPointItems(items => items.filter(item => item.id !== selected.id)); setSelected(undefined); setNotice('地点を削除しました') }} />}</MapPlaceholder><div className="mt-2 flex flex-wrap justify-between gap-2 text-xs text-muted"><span>地図操作：クリックで地点を選択</span><span>地点を読み込んでいます... / 地点情報を取得できませんでした。もう一度お試しください。</span></div></section></div></main></>
}

export default function App() {
  return <Routes><Route path="/" element={<HomePage />} /><Route path="/login" element={<AuthPage />} /><Route path="/signup" element={<AuthPage signup />} /><Route path="/projects" element={<ProjectsPage />} /><Route path="/projects/new" element={<ProjectFormPage />} /><Route path="/projects/:id/edit" element={<ProjectFormPage editing />} /><Route path="/projects/:id" element={<MapPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>
}
